### ISSUE TITLE
SGgame Branch: Crash

### ISSUE THREAD

**Issue by AllianceSky-PS** [HoeenCoder/Wavelength#127]
1st crash:

```
The server needs to restart because of a crash: TypeError: this.room.log.push is not a function
at CommandContext.parse (C:\Users\Administrator\Desktop\Impulse-Server\chat.js:313:20)
Please restart the server.
```

2nd Crash:

`~Wavelength Server: The server has crashed: Error: Obsolete command; use room.sendMods. at BasicChatRoom.sendModCommand (C:\Users\Administrator\Desktop\Impulse-Server\rooms.js:122:27)`

Both crashes occur after last night's update from main.

**Comment by HoeenCoder** [comment]
First was fixed just a little while ago

I need more information on the second, whats the full stack trace (you can find it in `logs/errors.txt`)

**Comment by AllianceSky-PS** [comment]
Okay, I've checked the errors.text and i found this:
```
Error: Obsolete command; use room.sendMods
    at BasicChatRoom.sendModCommand (C:\Users\Administrator\Desktop\Impulse-Server\rooms.js:122:27)
    at CommandContext.start (C:\Users\Administrator\Desktop\Impulse-Server\tournaments\index.js:1257:15)
    at CommandContext.Chat.commands.tournament (C:\Users\Administrator\Desktop\Impulse-Server\tournaments\index.js:1606:19)
    at CommandContext.run (C:\Users\Administrator\Desktop\Impulse-Server\chat.js:452:28)
    at CommandContext.parse (C:\Users\Administrator\Desktop\Impulse-Server\chat.js:258:19)
    at Object.Chat.parse (C:\Users\Administrator\Desktop\Impulse-Server\chat.js:1127:17)
    at User.chat (C:\Users\Administrator\Desktop\Impulse-Server\users.js:1478:9)
    at Function.socketReceive (C:\Users\Administrator\Desktop\Impulse-Server\users.js:1700:12)
    at Worker.worker.on.data (C:\Users\Administrator\Desktop\Impulse-Server\sockets.js:53:11)
    at emitTwo (events.js:130:20)

Additional information:
  user = Prince Sky
  room = lobby
  pmTarget = undefined
  message = /tour start
```
@HoeenCoder

**Comment by HoeenCoder** [comment]
Looks like you have outdated code on your server, the cause of the second crash is not on wavelength.
